---
version: "2.0"
services:
  tezos:
    image: tezos/tezos:latest
    expose:
      - port: 8732
        as: 8732
        to:
          - global: true
    args:
      - octez-node
      - "--network=sandbox"
profiles:
  compute:
    tezos:
      resources:
        cpu:
          units: 6
        memory:
          size: 16Gi
        storage:
          - size: 176Gi
  placement:
    dcloud:
      pricing:
        tezos:
          denom: uakt
          amount: 10000
deployment:
  tezos:
    dcloud:
      profile: tezos
      count: 1
